package com.zyndev;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.List;

/**
 * @author 张瑀楠 zyndev@gmail.com
 * @version 1.0
 * 2018/2/3 下午4;//51
 */
@Entity
@Data
@Table(name = "tb_param")

public class Param implements Serializable {

    private String Engine_MaxNJ; //;//480,
    private String InStat_SportSeat; // ;//有,
    private String UnderPan_RearSuspensionType; // ;//四连杆独立悬挂,
    private String InStat_HDC; // ;//无,
    private String Engine_EnvirStandard; // ;//国5,
    private String OutStat_ReMirrorElecTune; //;//有,
    private String InStat_CDPlayer; //;//无,
    private String OutStat_ReMirrorHot; // ;//有,
    private String Rear_seat_angle_adjustment; //;//无,
    private String InStat_Hud; //;//无,
    private String Engine_CylinderTMaterial; // ;//铝合金,
    private String nokey_into; //;//选配,
    private String OutStat_FBrushSensor; // ;//有,
    private String InStat_DVDPlayer; //;//无,
    private String InStat_LoudHailer;// ;//12,
    private String OutStat_FLightDazzle;//有,
    private String Engine_Exhaust;//2480,
    private String OutStat_ReMirrorDazzle;//有,
    private String Oil_FuelType;//汽油,
    private String Body_Louver;//无,
    private String Safe_KneeGasBag;//无,
    private String InStat_ComputerMonitors;//有,
    private String InStat_Bluetooth;//有,
    private String UnderPan_SpareWheelStandard;//无,
    private String UnderPan_TyrePressureWatcher;//有,
    private String Safe_BsadGasbag;//无,
    private String UnderPan_RimMaterial;//铝合金,
    private String InStat_CCEscreen;//无,
    private String Oil_FuelTab;//95号,
    private String Engine_Camshaft;//双顶置凸轮(DOHC),
    private String OutStat_FfogLamp;//无,
    private String InStat_CenterControlLock;//有,
    private String Engine_PowerSpeed;//5850-7000,
    private String InStat_AutoParking;//无,
    private String OutStat_FrontLightType;//LED,
    private String Safe_TCS;//有,
    private String InStat_Audiobrand;//Bang & Olufsen,
    private String OutStat_BBrushSensor;//无,
    private String InStat_GPS;//有,
    private String InStat_BCenterArmrest;//无,
    private String OutStat_CarWindow;//前电动窗,
    private String Safe_FsadGasbag;//有,
    private String SteeringAdjustmentLeftAndRight;//有,
    private String InStat_SteerTuneType;//无,
    private String InStat_FCenterArmrest;//有,
    private String InStat_SpeedCruise;//有,
    private String Engine_CylinderNum;//5,
    private String InStat_AutoPark;//有,
    private String Open_TipType;//硬顶,
    private String OutStat_FLightAutoClean;//无,
    private String Induction_trunk;//无,
    private String InStat_AirCType;//自动,
    private String Engine_MaxPower;//294,
    private String UnderPan_ZeroPressureDrive;//无,
    private String InStat_TrunkType;//无,
    private String Privacy_glass;//无,
    private String OutStat_BackCurtain;//无,
    private String UnderPan_Startandstopsystem;//有,
    private String Perf_AccelerateTime;//3.7,
    private String Lane_Departure;//选配,
    private String InStat_TemperSubCount;//有,
    private String UnderPan_TransmissionType;//双离合,
    private String InStat_FaceMirror;//有,
    private String Engine_ValvePerCylinder;//4,
    private String Liquid_crystal_instrument_panel;//有,
    private String Car_RepairPolicy;//三年或10万公里,
    private String InStat_3rdRowSeats;//无,
    private String UnderPan_RRadar;//有,
    private String OutStat_FLightDelay;//有,
    private String InStat_UphillAuxiliary;//无,
    private String OutStat_ReMirrormemory;//无,
    private String Safe_FheadGasbag;//有,
    private String Perf_DriveType;//全时四驱,
    private String UnderPan_FrontTyreStandard;//245/35 R19,
    private String InStat_blindspotdetection;//选配,
    private String InStat_SteerMaterial;//真皮/皮革,
    private String OutStat_atmosphereLight;//有,
    private String InStat_DSeatProp;//有,
    private String InStat_ElectricSeatMemory;//无,
    private String Safe_DriverGasBag;//有,
    private String seat_height_adjustable;//有,
    private String UnderPan_DriveAsistTurn;//电动,
    private String Safe_BheadGasbag;//无,
    private String OutStat_SportsAppearanceKit;//有,
    private String InStat_BEscreen;//无,
    private String UnderPan_RImage;//有,
    private String InStat_DASeatTuneType;//电动,
    private String UnderPan_ForwardGearNum;//7,
    private String Steering_Wheel_hot;//无,
    private String OutStat_TopSnelf;//无,
    private String Safe_EATS;//有,
    private String InStat_ReadingLight;//有,
    private String InStat_PositioningInteractiveServices;//无,
    private String Engine_NJSpeed;//1700-5850,
    private String Engine_horsepower;//400,
    private String OutStat_AvoidNipHead;//全车车窗,
    private String OutSet_Length;//4194,
    private String OutStat_FLightSteer;//有,
    private String InStat_SteerMomery;//无,
    private String Perf_Seatscope;//4,
    private String OutStat_DaytimeRunningLights;//LED,
    private String carId;//40758,
    private String InStat_SteeringAdjustmentUpAndDown;//有,
    private String Safe_EBD;//有,
    private String OutStat_SecondRowCurtain;//无,
    private String Engine_CylinderRank;//L型,
    private String Safe_EBA;//有,
    private String InStat_BSeatLieRate;//6/4,
    private String OutSet_Height;//1367,
    private String OutStat_Corneringlights;//有,
    private String OutSet_WheelBase;//2502,
    private String InStat_SeatKnead;//无,
    private String UnderPan_ParkingBrake;//电子驻车制动,
    private String InStat_SeatMaterial;//真皮,
    private String UnderPan_CentralDiffLock;//无,
    private String InStat_ActiveSafetySystems;//无,
    private String Engine_Location;//前置,
    private String Body_LouverOCType;//无,
    private String InStat_AIgnitionSys;//选配,
    private String Perf_Weight;//1490,
    private String InStat_AirCondPollenFilter;//有,
    private String Engine_InhaleType;//增压,
    private String Safe_ABS;//有,
    private String AirCondition_AirPurification;//无,
    private String InStat_BSeatTuneType;//,
    private String InStat_DSeatTuneType;//有,
    private String OutStat_FLightHeightTune;//有,
    private String UnderPan_FrontBrakeType;//通风盘,
    private String InStat_PanoramicCamera;//无,
    private String InStat_NightVisionSystem;//无,
    private String OutStat_UV_InsulatinGlass;//有,
    private String InStat_ElectricPick_upDoors;//无,
    private String OutStat_ReMirrorFold;//有,
    private String InStat_BeltBag;//无,
    private String Engine_AddPressType;//涡轮增压,
    private String Perf_MaxSpeed;//250,
    private String InStat_BleakAirNum;//无,
    private String Safe_BeltReminder;//有,
    private String InStat_AdjustableShoulderSupport;//无,
    private String UnderPan_Airmatic;//无,
    private String Body_Doors;//2,
    private String UnderPan_RearTyreStandard;//245/35 R19,
    private String UnderPan_PRadar;//有,
    private String InStat_Rckey;//有,
    private String Perf_ZongHeYouHao;//8.4,
    private String Engine_ExhaustForFloat;//2.5,
    private String Safe_SubDriverGasBag;//有,
    private String InStat_carFridge;//无,
    private String InStat_BCarShelf;//无,
    private String InStat_ChildSeatFix;//有,
    private String UnderPan_SuspensionHeightControl;//无,
    private String Body_Struc;//承载式,
    private String OutStat_FLightClose;//有,
    private String OutSet_Width;//1832,
    private String InStat_MultiFuncSteer;//有,
    private String InStat_DSeatHot;//前排座椅,
    private String Oil_FuelCapacity;//55,
    private String Engine_CylinderMaterial;//铝合金,
    private String UnderPan_RearBrakeType;//通风盘,
    private String UnderPan_DSC;//有,
    private String InStat_Automaticcruise;//无,
    private String InStat_SeatHeat;//无,
    private String UnderPan_FrontSuspensionType;//麦弗逊式独立悬挂,
    private String Oil_SupplyType;//混合喷射,
    private String InStat_BAirCSystem;//无,
    private String InStat_OverallActiveSteeringSystem;//无

    private CarParam carParam;

    private List<CarColor> CarColorList;
}
